### PR TITLE
Upgrade from bootstrap 3 to bootstrap 5

### PR DESCRIPTION
**Pull request by esirK**
## Description

Upgrades from bootstrap 3 to bootstrap 5

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (non-breaking change which does not add visible functionality but improves code quality)
- [ ] This change requires a documentation update

###### Home Page
Screenshot 2022-04-21 at 12 29 12

###### Home Page
Screenshot 2022-04-21 at 12 29 58

###### Report Surgeon
Screenshot 2022-04-21 at 12 33 09

###### Home Page

Screenshot 2022-04-21 at 12 33 38

#### Navigation
Screenshot 2022-04-21 at 12 34 44

#### Report Surgeon
Screenshot 2022-04-21 at 12 35 08

#### Get Legal
Screenshot 2022-04-21 at 12 35 24

#### Find Surgeons in your Area

Screenshot 2022-04-21 at 12 35 43

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽 ... Looks good.

----------------

I think the two sites have visible differences that _I don't think_ we were going for at this stage. Sample pages:

S1

S2

Or is just on my end?

**Comment by esirK** [comment]
> 👍🏽 ... Looks good.
> 

> Or is just on my end?

Not really on your end but I thought we were to improve the whole platform including how it looked(maintaining current functionality)?
If not it can be changed since it's mainly color and layout direction.

**Comment by kilemensi** [comment]
> > 👍🏽 ... Looks good.
> 
> > Or is just on my end?
> 
> Not really on your end but I thought we were to improve the whole platform including how it looked(maintaining current functionality)? If not it can be changed since it's mainly color and layout direction.

I believe there will be a tiny bit of UI redesign before relaunching in June @esirK. I therefore think we should stick to the current design as much as possible so that we're 💯 sure we haven't accidentally broken anything.

**Comment by esirK** [comment]
@kilemensi  I've done the updates and attached new screenshots.

**Comment by esirK** [comment]
@kilemensi  I think it's ready for re-review

**Review by kilemensi — COMMENTED** [review]
👍🏽 ... Looks good

------

### Mobile

Navigation is off... the logo as well as the language/menu buttons and alignment
M2

Size of homepage call to actions is off... Especially the last one
M1

First call to action (Registered) alignment is off and I'm getting `EN` one when I should be getting `XH`
M3

The last call to action (Find) also opens a misaligned form
M4


### Desktop

Big thing on desktop is the form size and alignment is off compared to the current site.
D1

**Review by kilemensi — COMMENTED** [review]
👍🏽 ... Much much better on desktop. Didn't notice anything out of place in my quick review.


The only issue is now on mobile where we have 👇🏽 
S

**Comment by esirK** [comment]
@kilemensi 
For 
>I think the only issue that's still left on Desktop is 👇🏽 form:

Is this from the latest code? From the attached photo even the navigation alignment seems off but on my end everything looks good.

> ... and the dropdown doesn't work on both mobile and desktop.

For this, you need to have actual data In the database.

**Comment by kilemensi** [comment]
> Is this from the latest code? From the attached photo even the navigation alignment seems off but on my end everything looks good.
> 

Unless my repo is messed up @esirK, it tells me I'm running latest code. Let me make a fresh clone and try again.

> For this, you need to have actual data In the database.
>
Back in the days we used to have DB dumps we shared and used for testing... I wonder what happened 🤔

**Comment by kilemensi** [comment]
Yeah, my local changes were a bust, I've updated the review @esirK : https://github.com/CodeForAfrica/HealthTools.ZA-Ezolwaluko/pull/3#pullrequestreview-954351449

**Comment by esirK** [comment]
> Yeah, my local changes were a bust, I've updated the review @esirK : [#3 (review)](https://github.com/CodeForAfrica/HealthTools.ZA-Ezolwaluko/pull/3#pullrequestreview-954351449)

I think it's ready for re-review @kilemensi

**Review by kilemensi — APPROVED** [review]
🚀 

---

There are still UI inconsistencies but since we know it works, we'll address them when the time to comes to deploy this version.

**Pull request merged**
